


#ifndef CONSTANTS_H_
#define CONSTANTS_H_

// Window Size
#define WORLD_WINDOW_WIDTH 550
#define WORLD_WINDOW_HEIGHT 380
#define MAGNIFICATION 2

#define DOWN 0
#define UP 1
#define NONE -1
#define LEFT 2
#define RIGHT 3

#define PLAYER_SPEED 4
#define FALLING_SPEED 4
#define CLIMBING_SPEED 3
static const float JUMP_SPEED = 3.3;
#define JUMP_MAX_HEIGHT 22
#define ANIMATION_REFRESH_INTERVAL 2
#define CLIMBING_ANIMATION_REFRESH_INTERVAL 4

#define PLAYER_ANIMATION_0_WIDTH 11
#define PLAYER_ANIMATION_0_HEIGHT 42
#define PLAYER_ANIMATION_0_LOOKING_LEFT_COMPENSATION 4


#define GROUND_Y 140
#define TUNNEL_FLOOR_Y 32

#define WAIT_TIME 25

#define SPACE_BAR 32


#endif